### ISSUE TITLE
auto-detect ruby version and use appropriate ruby base image in Dockerfile

### ISSUE THREAD

**Issue by icevans** [unnamed-paas/paas#4]

**Comment by bharatagarwal** [comment]
**A note on whether to use `.ruby_version` or `Gemfile` for detecting the ruby version:**

The `Gemfile` is a feature of bundler, while `.ruby_version` was introduced by rvm and copied by other ruby version managers. 

Since we're confident we'll be using a Gemfile to manage dependencies, it makes sense to get the version from there.

**Comment by jkulton** [comment]
It may be worth seeing if there are any libraries out there that can parse a Gemfile and get metadata about it. I have no clue if anything like that exists, though.

**Comment by bharatagarwal** [comment]
We may also decide to support only certain versions of ruby if that makes things easier.
